### PR TITLE
Add loading login form instead blank screen

### PR DESCRIPTION
**Pull request by Joozty**
Adds a login page with a loading spinner to avoid the blank screen during data retrieving.

### CODE REVIEW

**Comment by Joozty** [comment]
> Do you restore previous view if loading gets an error?

Page gets reloaded if the wrong credentials are typed in.

Also, the form is empty when showed in iframe. There is nothing we can do about it. (we don't know username) but it's still better than a blank screen.

**Comment by viktor-yakubiv** [comment]
Could we please discuss #185?

**Comment by viktor-yakubiv** [comment]
I get it, you just fake it, right? You do redirect anyway but to avoid blank screen you render login. Is this correct?

**Comment by Joozty** [comment]
> I get it, you just fake it, right? You do redirect anyway but to avoid blank screen you render login. Is this correct?

Yes, correct and I handled all cases of the blank screen.

**Pull request merged**
