### PR TITLE
Fix pages look and scroll behaviour

### LINKED ISSUE #42: Scrollbar hidden under app bar
I am not sure whether it's a bug or desired behavior. I incline more to 🐞. 

Scroll

### PR DESCRIPTION
**Pull request by viktor-yakubiv**
1. Fixes look and spacing back.
1. Fixes scrollbar appearance. Closes #42 

On top of #57

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
@Joozty let me know if you can live with such interface for some time. I do not like it but I do not know how to make it better for this time.

@PMRuma this is changes you mentioned, almost all.

**Comment by viktor-yakubiv** [comment]
@Joozty I resolved conflicts and aligned this branch. Repeating question:
> @Joozty let me know if you can live with such interface for some time. I do not like it but I do not know how to make it better for this time.

**Comment by viktor-yakubiv** [comment]
I thought I did like you recommend in the issue.

I mean props passing from Main HOC in the Application to the Card in pages. This is not clear

**Comment by Joozty** [comment]
> Well, I think it's quite complex and it took me some time to understand it. Now I understand it but when I look at the code in one month I may not understand again...

@viktor-yakubiv This is my feeling about Main HOC and passing props....

**Pull request merged**
