### PR TITLE
Rename deposit dates navigation item

### PR DESCRIPTION
**Pull request by viktor-yakubiv**
I found it's quite hard to rename id's and change the URL to reflect this change. We will have it deposit-dates everywhere.

### CODE REVIEW

**Comment by Joozty** [comment]
I would prefer to rename it everywhere. It shouldn't be so hard.

**Comment by viktor-yakubiv** [comment]
It worth to take marketing decision immediately and then think about infrastructure.

**Comment by Joozty** [comment]
Well, it takes max 10minutes to rename everything so why do it in new PR? I can do it. No problem.

**Comment by viktor-yakubiv** [comment]
I do not feel expert in doing so. Also, I had bad experience doing a 30m task whole day yesterday.

If you want to rename, go for it. I do not think it's necessary for this moment and it may create breaking changes for other PRs.

**Pull request merged**
