### PR TITLE
Fix password reset

### PR DESCRIPTION
**Pull request by Joozty**

### CODE REVIEW

**Comment by Joozty** [comment]
@viktor-yakubiv Any reason for using [label class instead of element selector](https://github.com/oacore/design/blob/master/src/elements/forms/text-field.css#L125)? I am not sure if the third commit shouldn't be rather fixed in design. Hmm?

**Comment by viktor-yakubiv** [comment]
I should have work according to [this line](https://github.com/oacore/design/blob/master/src/elements/forms/text-field.css#L247) but I have no idea, what is the problem there.

**Comment by Joozty** [comment]
I am ok with the solution. I was just curious. 🙂

**Comment by viktor-yakubiv** [comment]
There something is wrong when the form is filled up. When you type password and press 'Tab', the label returns back. I am not sure it's either missing classes in the HTML or the bug in Design.

**Comment by Joozty** [comment]
The third commit was supposed to fix it. I just forgot to fix login page.

**Comment by viktor-yakubiv** [comment]
It's not a problem, it can be done separately

**Comment by Joozty** [comment]
Can you please double-check on master branch?

**Pull request merged**
