### PR TITLE
Add Issues tab

### PR DESCRIPTION
**Pull request by Joozty**

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
I checked the preview. Despite I did not see any data, your design proposal is really good! I would not even think about this layout! 👍

**Comment by viktor-yakubiv** [comment]
@Joozty what repository should I check? I cannot find any data

**Comment by Joozty** [comment]
So dataprovider 5 should be good choice. Maybe ask Matteo to assign it to you. 

I haven't really tested last commit yet. Since API is hanging since the morning. So there may be some small bugs. :(

**Comment by viktor-yakubiv** [comment]
I kind of finished and wonder if you dear @oacore/dashboard have any feedback. I am afraid we should preview it locally during these days because of deployment issues.

**Comment by viktor-yakubiv** [comment]
@Joozty do you have time to help me solve conflicts? I assume it's because of the table changed.

**Comment by Joozty** [comment]
Here is my approval. ✔️ Feel free to merge if you are not going to add anything else.

**Comment by viktor-yakubiv** [comment]
There is an error with date formatting. I will handle it and merge one by one. I wonder if we should do an early release after this. @oacore/dashboard what do you think?

**Comment by viktor-yakubiv** [comment]
I explored the error, it happens because of inconsistent [non-standard date formatting](https://stackoverflow.com/a/4310986/7205866) in the API response in Safari but is fine in Chrome and should be fine in Firefox.

**Comment by Joozty** [comment]
Please report this to Jira or use dayjs if it helps. :)

**Pull request merged**
