### PR TITLE
Add basic Card component

### PR DESCRIPTION
**Pull request by viktor-yakubiv**
I developed basic card component but I have not tested it. @Joozty what is the best place to integrate it?

### CODE REVIEW

**Comment by Joozty** [comment]
I guess you can test it [here](https://github.com/oacore/dashboard/blob/master/pages/index.jsx#L7) with some mocked data.

**Comment by viktor-yakubiv** [comment]
The Overview page is not going to be a part of the MVP so I would not like to spend any time on it. I will find something and let you know. Thank you!

**Comment by Joozty** [comment]
@viktor-yakubiv Ok then. Please rebase and I think it can be merged.

**Comment by Joozty** [comment]
Card tested here https://dashboard-git-deposit-dates.oacore.now.sh/deposit-dates

**Pull request merged**
