### PR TITLE
Bump package versions [March]

### PR DESCRIPTION
**Pull request by viktor-yakubiv**
- @babel/core from 7.8.0 to 7.8.6
- @babel/plugin-proposal-class-properties from 7.8.0 to 7.8.3
- @babel/plugin-proposal-decorators from 7.8.0 to 7.8.3
- @sentry/browser from 5.11.2 to 5.13.0
- @sentry/node from 5.11.2 to 5.13.1
- dayjs from 1.8.19 to 1.8.21
- husky from 4.2.1 to 4.2.3
- lint-staged from 10.0.7 to 10.0.8
- mobx-react from 6.1.4 to 6.1.8
- eslint from 6.7.1 to 6.8.0
- eslint-plugin-import from 2.19.1 to 2.20.1
- eslint-plugin-prettier from 3.1.1 to 3.1.2
- eslint-plugin-react from 7.17.0 to 7.18.3
- eslint-plugin-react-hooks from 2.3.0 to 2.5.0
- babel-eslint from 10.0.3 to 10.1.0
- react from 16.12.0 to 16.13.0
- react-dom from 16.12.0 to 16.13.0
- next from 9.1.4 to 9.2.2
- next-images from 1.2.0 to 1.3.1
- stylelint-prettier from 1.1.1 to 1.1.2
- webpack from 4.41.5 to 4.42.0

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
@Joozty here is as many as dependabot managed to merge today. I squashed all of them and waiting for Next 🙂

**Comment by Joozty** [comment]
Wouldn't be better to review every package separately next time? This pull request should be just merged without any review. Every breaking change should be handled on it's own.

I mean if you did it then merge it and don't wait for my review. :)

**Comment by Joozty** [comment]
Never mind. Sorry I didn't notice your comment.

**Comment by viktor-yakubiv** [comment]
I want to automate as much as possible. Probably, I will enable minor updates to be merged automatically but major updates only manually.

These all are minot but I have not checked it at all.

**Pull request merged**
