### PR TITLE
Sentry integration

### PR DESCRIPTION
**Pull request by Joozty**
Example of error with user metadata [here](https://sentry.io/organizations/oacore/issues/1484745460/?project=2091955&query=is%3Aunresolved)

Last commit has to be dropped before merge. It's just demenstration of error boundary message.

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
Does it work?

**Comment by Joozty** [comment]
Yes, why? (Sentry is disabled for now.sh and localhost)

**Comment by viktor-yakubiv** [comment]
Just clarifying.

I would like to avoid `dotenv` if favour of present/absent environmental variable. Everything else looks good to me.

Could you please remove the last testing commit and then feel free merge? Or do you want to push that commit too?

**Comment by Joozty** [comment]
> I would like to avoid dotenv if favour of present/absent environmental variable. Everything else looks good to me.

I wouldn't do that. When I want to test something on localhost it's easier for me to change .env file instead of exporting my env variable. I may even forget to "unexport" that variable after a test. Besides, you don't need to use that. You can freely export your variables. Also dotenv doesn't affect page size...

**Comment by viktor-yakubiv** [comment]
It's matter of taste. I prefer one, you another. It's okay.

However, your `.env` file is ignored so you can only know it exists or has been changed if you manually check it. It has the same cons as simple exporting. 

By the way, you export for a single terminal session. Because it does not persist you have fresh environment for each time you close and open terminal window.

**Comment by Joozty** [comment]
> By the way, you export for a single terminal session. Because it does not persist you have fresh environment for each time you close and open terminal window.

Unfortunately, I don't run it in terminal. I have it configurated in my IDE and if I need to change it I need to go to configuration settings and change ENV variables there. This is much simpler for me but I agree that .env is not tracked and I may forget to remove it from there.

**Pull request merged**
