### PR TITLE
Rewrite table to functional component

### PR DESCRIPTION
**Pull request by Joozty**

### CODE REVIEW

**Comment by Joozty** [comment]
@viktor-yakubiv It's basically the second commit https://github.com/oacore/dashboard/pull/326/commits/82eb34f66dbe1a681ef2ca86316adcf4f1c3fa1e


The idea is to make the table as dumb as possible. It's kind of part of https://github.com/oacore/dashboard/issues/260. There should be two table hooks - `useDynamicData()` and `useStaticData()`. First mentioned is created in second commit. The later one will in the near future as we want to show invited people in settings and these data is static.

**Comment by Joozty** [comment]
@viktor-yakubiv Sorry it's one big commit. I didn't have a clear idea of how to refactor it so I used different approaches and everything ended up in one commit.

I don't expect you to go through the whole code. Maybe just take a brief look if it is now more readable. I am not sure about it, to be honest. I managed to create small component/hooks and reduce the size of the table file. The most important change is useDymanicData hook. I moved data loading outside of the table and all related state is passed as a props. This can help us to use static data as well and eventually removed `Pages` (although I don't know how to replace it with something better)

**Comment by Joozty** [comment]
I will wait and handle conflicts here. No problem. Thanks for looking into it. :)

**Comment by Joozty** [comment]
I hope I resolved all conflicts correctly. Feel free to assign any bug with a table directly to me.

**Comment by viktor-yakubiv** [comment]
Thanks a lot for maintaining all the conflicts for such a long time! 👍

I hope this PR is as big improvement as we hope 😄

**Pull request merged**
